header:
  bgImg: https://i.imgur.com/4Ofhqe6.png
  color: '#ffffff'
  addSite: '添加新网站'

# colors reference: https://coolors.co/fbc3c8-ffface-e4f9d1-bbf2ed-adccd9
categories:
  search:
    title: 搜索工具
    bgColor: '#E4F9D1'
  development:
    title: 开发工具
    bgColor: '#FFFACE'
  icons:
    title: 图标库
    bgColor: '#BBF2ED'

navigation:
  icons:
    web: fas fa-external-link-alt
