header:
  bgImg: https://i.imgur.com/4Ofhqe6.png
  color: '#ffffff'
  addSite: '添加新网站'

categories:
  search:
    bgColor: '#E4F9D1'
    title: 搜索工具
  development:
    bgColor: '#FFFACE'
    title: 开发工具
  icons:
    bgColor: '#BBF2ED'

navigation:
  icons:
    web: fas fa-external-link-alt
